# Generated by Django 5.1.5 on 2025-02-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0002_customuser_data_nascimento_customuser_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('idade_gestacional', models.IntegerField(help_text='Idade gestacional em semanas')),
                ('data_ultima_menstruacao', models.DateField(blank=True, null=True)),
                ('data_prevista_parto', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
