# Generated by Django 5.1.5 on 2025-02-08 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0003_gestante'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestante',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='emg_ctt_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='emg_ctt_parentesco',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='emg_ctt_telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='etnia',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='nome_companheiro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='nome_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='num_nis',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='num_sus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_antecedentes',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_info',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_instrucao',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_nome_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_perssaoarterial',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='parceiro_peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_abo_data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_abo_resultado',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_glicemia_data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_glicemia_resultado',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_hemograma_data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_hemograma_resultado',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_hepatite_data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_hepatite_resultado',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_hiv_data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_hiv_resultado',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_sifilis_data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_sifilis_resultado',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_vdrl_data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gestante',
            name='pcr_exame_vdrl_resultado',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='ponto_referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestante',
            name='raca',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
