# Generated by Django 5.1.5 on 2025-02-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0005_alter_gestante_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestante',
            name='emg_ctt_parentesco',
            field=models.CharField(blank=True, choices=[('', 'Selecione o Parentesco'), ('companheiro', 'Companheiro(a)'), ('familiar', 'Familiar'), ('Amigo', 'Amigo(a)'), ('outro', 'Outro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='parceiro_antecedentes',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='parceiro_info',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
