# Generated by Django 5.1.5 on 2025-02-08 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0007_remove_gestante_idade_gestacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestante',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='emg_ctt_parentesco',
            field=models.CharField(blank=True, choices=[('', 'Selecione o Parentesco'), ('companheiro', 'Companheiro(a)'), ('familiar', 'Familiar'), ('amigo', 'Amigo(a)'), ('outro', 'Outro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_abo_data',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_glicemia_data',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_hemograma_data',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_hepatite_data',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_hiv_data',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_sifilis_data',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_vdrl_data',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
