# Generated by Django 5.1.5 on 2025-02-08 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0008_alter_gestante_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_abo_data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_glicemia_data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_hemograma_data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_hepatite_data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_hiv_data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_sifilis_data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='pcr_exame_vdrl_data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
