# Generated by Django 5.1.5 on 2025-02-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0009_alter_gestante_cpf_alter_gestante_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestante',
            name='data_ultima_menstruacao',
        ),
    ]
