# Generated by Django 5.1.5 on 2025-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0010_remove_gestante_data_ultima_menstruacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestante',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
