# Generated by Django 5.1.5 on 2025-02-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0011_alter_gestante_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestante',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=14, null=True, unique=True),
        ),
    ]
