# Generated by Django 5.1.5 on 2025-02-13 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0013_gestante_alta_maternidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parto', models.CharField(blank=True, max_length=55, null=True)),
                ('sangramento', models.CharField(blank=True, max_length=55, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=55, null=True)),
                ('intercorrencias', models.CharField(blank=True, max_length=55, null=True)),
                ('alta_maternidade', models.CharField(blank=True, max_length=55, null=True)),
                ('peso_alta', models.CharField(blank=True, max_length=55, null=True)),
                ('visita_domiciliar', models.CharField(blank=True, max_length=55, null=True)),
                ('nascimento', models.CharField(blank=True, choices=[('', 'Selecione o Parentesco'), ('prematuro', 'Prematuro'), ('atermo', 'A termo')], max_length=15, null=True)),
                ('nome_bebe', models.CharField(blank=True, max_length=55, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=55, null=True)),
                ('data_nascimento_bebe', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('local_nascimento', models.CharField(blank=True, max_length=55, null=True)),
                ('profissionais', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='alta_maternidade',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='data_nascimento_bebe',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='intercorrencias',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='local_nascimento',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='nome_bebe',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='peso_alta',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='profissionais',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='sangramento',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='tipo_parto',
        ),
        migrations.RemoveField(
            model_name='gestante',
            name='visita_domiciliar',
        ),
    ]
