# Generated by Django 5.1.5 on 2025-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0015_posparto_cpf_mae_posparto_data_nascimento_mae'),
    ]

    operations = [
        migrations.AddField(
            model_name='posparto',
            name='hora_nascimento_bebe',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posparto',
            name='data_nascimento_bebe',
            field=models.DateField(blank=True, null=True),
        ),
    ]
