# Generated by Django 5.1.5 on 2025-02-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0016_posparto_hora_nascimento_bebe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gestante', models.CharField(blank=True, max_length=255, null=True)),
                ('data_nascimento_gestante', models.DateField(blank=True, null=True)),
                ('cpf_gestante', models.CharField(blank=True, max_length=14, null=True)),
                ('placa_viavel', models.CharField(blank=True, max_length=55, null=True)),
                ('placa_viavel_data', models.DateField(blank=True, null=True)),
                ('placa_sangramento', models.CharField(blank=True, max_length=55, null=True)),
                ('placa_sangramento_data', models.DateField(blank=True, null=True)),
                ('placa_sangramento_sondagem', models.CharField(blank=True, max_length=55, null=True)),
                ('placa_sangramento_sondagem_data', models.DateField(blank=True, null=True)),
                ('calculo_dentario', models.CharField(blank=True, max_length=55, null=True)),
                ('calculo_dentario_data', models.DateField(blank=True, null=True)),
                ('mobilidade', models.CharField(blank=True, max_length=55, null=True)),
                ('mobilidade_data', models.DateField(blank=True, null=True)),
                ('perda_insercao', models.CharField(blank=True, max_length=55, null=True)),
                ('perda_insercao_data', models.DateField(blank=True, null=True)),
                ('plano_tratamento', models.CharField(blank=True, max_length=55, null=True)),
                ('tratamento_data', models.DateField(blank=True, null=True)),
                ('tratamento_dente', models.CharField(blank=True, max_length=55, null=True)),
                ('procedimento_realizado', models.CharField(blank=True, max_length=55, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=55, null=True)),
                ('tratamento_necessario', models.CharField(blank=True, max_length=55, null=True)),
                ('encaminhamento', models.CharField(blank=True, max_length=55, null=True)),
                ('retorno', models.CharField(blank=True, max_length=55, null=True)),
                ('plano_cuidado', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
