# Generated by Django 5.1.5 on 2025-02-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0018_alter_odonto_calculo_dentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posparto',
            name='data_nascimento_mae',
        ),
        migrations.RemoveField(
            model_name='posparto',
            name='nome_mae',
        ),
    ]
