# Generated by Django 5.1.5 on 2025-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0019_remove_posparto_data_nascimento_mae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odonto',
            name='data_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odonto',
            name='dentes_selecionados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
