# Generated by Django 5.1.5 on 2025-02-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0020_odonto_data_consulta_odonto_dentes_selecionados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odonto',
            name='data_consulta',
        ),
        migrations.RemoveField(
            model_name='odonto',
            name='data_nascimento_gestante',
        ),
        migrations.RemoveField(
            model_name='odonto',
            name='dentes_selecionados',
        ),
        migrations.RemoveField(
            model_name='odonto',
            name='nome_gestante',
        ),
    ]
