# Generated by Django 5.1.5 on 2025-02-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0021_remove_odonto_data_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('idade_gestacional', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unidade_saude', models.CharField(blank=True, max_length=55, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=55, null=True)),
                ('nome_profissional', models.CharField(blank=True, max_length=255, null=True)),
                ('crm', models.CharField(blank=True, max_length=10, null=True)),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthybaby.gestante')),
            ],
        ),
    ]
