# Generated by Django 5.1.5 on 2025-02-18 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0021_remove_odonto_data_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestante', models.CharField(blank=True, max_length=11, null=True)),
                ('data_consulta', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_prevista_parto', models.DateField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf_gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthybaby.gestante')),
            ],
        ),
    ]
