# Generated by Django 5.1.5 on 2025-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0022_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profissao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
