# Generated by Django 5.1.5 on 2025-02-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0022_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cpf_gestante',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_prevista_parto',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='telefone',
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='gestante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthybaby.gestante'),
        ),
    ]
