# Generated by Django 5.1.5 on 2025-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0023_remove_consulta_cpf_gestante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='especialidade',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='idade_gestacional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_profissional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='unidade_saude',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
