# Generated by Django 5.1.5 on 2025-02-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0024_consulta_especialidade_consulta_idade_gestacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
