# Generated by Django 5.1.5 on 2025-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0025_alter_consulta_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='crm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
