# Generated by Django 5.1.5 on 2025-02-24 12:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0026_consulta_crm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='crm',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='gestante',
            field=models.ForeignKey(db_column='cpf_gestante', on_delete=django.db.models.deletion.CASCADE, to='healthybaby.gestante', to_field='cpf'),
        ),
    ]
