# Generated by Django 5.1.5 on 2025-02-24 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0027_remove_consulta_crm_alter_consulta_data_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='gestante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthybaby.gestante'),
        ),
    ]
