# Generated by Django 5.1.5 on 2025-02-24 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0028_alter_consulta_data_consulta_alter_consulta_gestante'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='crm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
