# Generated by Django 5.1.5 on 2025-02-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthybaby', '0029_consulta_crm_alter_consulta_data_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='crm',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='gestante',
            field=models.ForeignKey(db_column='cpf_gestante', on_delete=django.db.models.deletion.CASCADE, to='healthybaby.gestante', to_field='cpf'),
        ),
    ]
